###Autenticación de usuario(Login)
POST http://localhost:8081/api/v1/auth/login
Accept: application/json
Content-Type: application/json

{
    "username": "patricia.castillo",
    "password": "PC2026!"
}

###CERRAR SESION
POST http://localhost:8081/api/v1/auth/logout
Accept: application/json
Content-Type: application/json
Authorization: Bearer 2|A5pAfqJxpiuP1t1QiNqUVwYbsQOlg6QpnWo2u6AU6dc12e5c
