### Obtener todos los servicios
GET http://localhost:8081/api/servicios
Authorization: bearer 1|ZO900hRoOi7N9yEWdi6LTpkQNynbIJ832LgpQemo75ac86ea
Content-Type: application/json
Accept: application/json

### Crear un servicio
POST http://localhost:8081/api/servicios
Authorization: Bearer 2|9aZWrr4Ev0AMt89mxbWO69XFS2x5fJ7ffISDTjn726e3114a
Content-Type: application/json

{
    "codigo": "S20",
    "nombre": "Servicio de Prueba",
    "unidad": "Día",
    "precio": 100.00,
    "porEv": false,
    "nota": "Prueba de nuevos campos"
}

### Obtener un servicio específico
GET http://localhost:8081/api/servicios/1
Authorization: Bearer {{token}}

### Actualizar un servicio
PUT http://localhost:8081/api/servicios/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nombre": "Limpieza Premium",
    "descripcion": "Incluye desinfección total",
    "precio": 750.00
}

### Eliminar un servicio
DELETE http://localhost:8081/api/servicios/1
Authorization: Bearer {{token}}
